name: Migrate and Deploy via Vercel Hook

on:
  push:
    branches:
      - main  # or your production branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Run Prisma Migrations
        env:
          POSTGRES_URL: ${{ secrets.POSTGRES_URL_NON_POOLING }}
        run: npx prisma migrate deploy

      - name: Trigger Vercel Deploy
        run: |
          echo "Triggering Vercel deploy..."
          curl -X POST "${{ secrets.VERCEL_DEPLOY_HOOK_URL }}"
